#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp_1.Resource", IsApplication=true)]

namespace AndroidApp_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int Button1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int Button2 = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int EditText1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int EditText2 = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int MyButton = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int MyEditText1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int MyEditText2 = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int btnClick1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int btnClick2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnClick3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnMultiSelect = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnSingleSelect = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int rg1 = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int txtPassword_Login = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int txtUsername_Login = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AhnLayout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int Click1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Click2 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Click3 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Click4 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Click5 = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int ClickMe = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Copy = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Love = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int LoveFeng = 2130968580;
			
			// aapt resource value: 0x7f040015
			public const int Password_Login = 2130968597;
			
			// aapt resource value: 0x7f040006
			public const int Paste = 2130968582;
			
			// aapt resource value: 0x7f040014
			public const int Username_Login = 2130968596;
			
			// aapt resource value: 0x7f040010
			public const int alertBtnNo = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int alertBtnYes = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int alertMessage = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int alertTitle = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int alertYes = 2130968591;
			
			// aapt resource value: 0x7f040017
			public const int btnCancel_Login = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int btnLogin_Login = 2130968598;
			
			// aapt resource value: 0x7f040011
			public const int love1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int love2 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int love3 = 2130968595;
			
			// aapt resource value: 0x7f040019
			public const int msg1_Login = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int msg2_Login = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int msg3_Login = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int password = 2130968605;
			
			// aapt resource value: 0x7f040018
			public const int title_Login = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int username = 2130968604;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
